apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

commonLabels:
  app.kubernetes.io/managed-by: "kustomize"
  app.kubernetes.io/version: "1.0.1-ae823wj"

resources:
  - deployment-demo-service.yaml
  - service-demo-service.yaml

patchesStrategicMerge:
- custom-env.yaml
